export const PageName = {
    ROOT: 'Root',
    LOADING: 'Loading',
    TAB_NAVIGATOR: 'TabNavigator',
    LOGIN: 'Đăng nhập',
    LOGOUT: 'Đăng xuất',
    EXIT: 'Thoát',
    REGISTER: 'Đăng ký',
    ACTIVATE_ACCOUNT_PAGE: 'Xác minh tài khoản',
    HOME: 'Trang chủ',
    CHAT: 'Chat',
    CHAT_DETAIL: 'ChatDetail',
    CHAT_PERSONAL: 'ChatPersonal',
    PROFILE: 'Profile',
    EDIT_PROFILE: 'Chỉnh sửa trang cá nhân',
    LIST_FRIENDS: 'Danh sách bạn bè',
    EDIT_USER: 'Chỉnh sửa thông tin cá nhân',
    CREATE_POST_PAGE: 'Thêm bài viết',
    POST_DETAIL_PAGE: 'Chi tiết bài viết',
    FRIEND_PROFILE: 'Trang cá nhân bạn bè',
    EDIT_POST_PAGE: 'Chỉnh sửa bài viết',
    SEARCH_PAGE: 'Tìm kiếm',
    NOTIFICATION_PAGE: 'Thông báo',
    SETTING_PAGE: 'Cài đặt',
};
